/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** module registration is done by the runtime, no need to explicitly do it now. */
export function fibonacci(n: number): number
/**
 * use `Fn`, `FnMut` or `FnOnce` traits to defined JavaScript callbacks
 * the return type of callbacks can only be `Result`.
 */
export function getCwd(callback: (arg0: string) => void): void
/** or, define the callback signature in where clause */
export function testCallback(callback: (arg0: string) => void): void
