global:
  scrape_interval: 15s
  scrape_timeout: 10s
scrape_configs:
  - job_name: notion-echo-metrics
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    static_configs:
      - targets:
        - 'localhost:8080'